### ISSUE TITLE
Plans for Python 2.7

### ISSUE THREAD

**Issue by jamespic** [hugovk/drop-python#27]
With the upcoming EOL for Python 2.7, it would be good to know whether and when this site will start recommending for projects to drop Python 2.7.

**Comment by hugovk** [comment]
There's already a page for Python 2.7 but it's not on the frontpage yet:

* https://hugovk.github.io/drop-python/2.7/

You can see all the versions it's tracking here:

* https://hugovk.github.io/drop-python/index2.html

So far I've only put versions on the frontpage once they're past EOL, but I may put 2.7 there earlier.

I recommend projects start planning now when to drop Python 2.7. Many have pledged to drop it before 2020, and some already have.

See also:

* https://python3statement.org
* https://python2woop.pw
* https://pythonclock.org

**Comment by hugovk** [comment]
Python 2.7 and 3.4 are now on the frontpage.
