### ISSUE TITLE
More backports

### ISSUE THREAD

**Issue by jayvdb** [hugovk/drop-python#29]
The list of backports can be partially obtained using https://github.com/jackmaney/python-stdlib-list/pull/28 

Using that, I found the following are missing from the `EXCLUDED_PACKAGES` list.

- [DateTime](http://pypistats.org/packages/datetime) - 6396758 - not the same?  Owned by Zope so in safe hands.  Installs to `DateTime` so doesnt conflict with `datetime`.
- [dataclasses](http://pypistats.org/packages/dataclasses) - 4177601
- [statistics](http://pypistats.org/packages/statistics) - 4262268
- [asyncio](http://pypistats.org/packages/asyncio) - 3097987
- [functools](http://pypistats.org/packages/functools) - 905303 - not a backport; created 2005; https://pypi.org/project/functools/#files
- [enum](http://pypistats.org/packages/enum) - 2741560
- [contextvars](http://pypistats.org/packages/contextvars) - 1291645
- [uuid](http://pypistats.org/packages/uuid) - 2070490
- [logging](http://pypistats.org/packages/logging) - 4527726
- [readline](http://pypistats.org/packages/readline) - 374841 - shouldnt be excluded as this is needed for ppl who cant compile readline into their binary
- [Resource](http://pypistats.org/packages/resource) - 1194645 - very different; PyPI package created 2014; should be delisted? :/
- [importlib](http://pypistats.org/packages/importlib) - 1458974
- [html](http://pypistats.org/packages/html) - 699354
- [pprint](http://pypistats.org/packages/pprint) - 720260 - junk upload?
- [faulthandler](http://pypistats.org/packages/faulthandler) - 842383
- [multiprocessing](http://pypistats.org/packages/multiprocessing) - 331224
- [email](http://pypistats.org/packages/email) - 269055
- [hashlib](http://pypistats.org/packages/hashlib) - 230497
- [AST](http://pypistats.org/packages/ast) - 405650 - Very different; Created 2017
- [wsgiref](http://pypistats.org/packages/wsgiref) - 231243

`pprint`, `resource` and `ast` should be excluded IMO, as I am sure their inclusion in the top packages is only due to having the same name as a stdlib package.  I think they should also be delisted from PyPI and other existing stdlib names prevented from being used (or an extra permission needed to control who can use those names) to prevent malicious uploads.

`DateTime` would probably not be on the list if it wasnt for the stdlib name clash.  Oddly, the 'used by' on https://github.com/zopefoundation/DateTime is quite high (7.2k) - I wonder if the GitHub stats are also skewed.  But it could be that the GitHub stats are correct, as this is Zope, and IMO it isnt worth delisting it from this project due to the Zope aspect - perhaps intentionally move it to the end of the list since its true relevance based on download count is highly suspect, so its appropriate position in the list is not knowable.

fwiw, the other stdlib names in the top list all appear to be 'safe'.
- [ipaddress](http://pypistats.org/packages/ipaddress) - 102211778
- [configparser](http://pypistats.org/packages/configparser) - 66829892
- [typing](http://pypistats.org/packages/typing) - 61522886
- [argparse](http://pypistats.org/packages/argparse) - 71515972
- [pathlib](http://pypistats.org/packages/pathlib) - 16293161

**Comment by hugovk** [comment]
Thanks for this!

I've only been adding things to the exclusion list when I've seen them show up as one the 360 here, and I see that the most downloaded of these ones (DateTime) is currently at 632 on [Top PyPI Packages](https://hugovk.github.io/top-pypi-packages/), and the next one (logging) is at 791, so at least they're unlikely to be relevant for a while.

6396758 - DateTime
4527726 - logging
4262268 - statistics
4177601 - dataclasses
3097987 - asyncio
2741560 - enum
2070490 - uuid
1458974 - importlib
1291645 - contextvars
1194645 - Resource
905303 - functools
842383 - faulthandler
720260 - pprint
699354 - html
405650 - AST
374841 - readline
331224 - multiprocessing
269055 - email
231243 - wsgiref
230497 - hashlib

I'm not aiming for a definitive list of exclusions, only those that appear in the 360, so this is useful for future reference. If you want, feel free to create a PR to exclude some that are definitely backports, although if they may never show up here I wouldn't put too much effort into that. Thanks again!

**Comment by jayvdb** [comment]
Ah, I am using the full list for my current analysis.  The problem is still relevant to https://github.com/hugovk/top-pypi-packages I guess.

For completeness, some other packages using stdlib names that look questionable / not backports, but need to recheck
- chunk
- dis
- formatter
- modulefinder
- secrets
- token

**Comment by hugovk** [comment]
I'm keeping the list at https://github.com/hugovk/top-pypi-packages vanilla with no changes at all, so people can use it as they wish. For example, maybe to find out how popular a backport is to decide whether to continue maintaining it. But thank you!
