### ISSUE TITLE
website not up-to-date

### ISSUE THREAD

**Issue by mayeut** [hugovk/drop-python#44]
I'm seeing `Last updated Friday, 27 May 2022, 06:35:17 UTC. (Updated hourly.)`.
Are the updates down for some reason ?

**Comment by hugovk** [comment]
Thanks, it had got stuck on the wrong branch, so couldn't find `crontash.sh` in `main`, likely following a network error.

I've updated the cron script so it switches back to `main` before starting, and it's now up-to-date.

https://hugovk.github.io/drop-python/

Thanks for the letting me know!
