### ISSUE TITLE
Wrong anchor in drop-python page

### ISSUE THREAD

**Issue by dvarrazzo** [hugovk/drop-python#52]
The end of life link in the [drop-python](https://hugovk.github.io/drop-python/) points to the `#branchstatus` anchor, which doesn't exist.

THIS IS A DEAD ANCHOR! (cit.)

What you might want to refer is to https://devguide.python.org/versions/#status-of-python-versions

Cheers!

**Comment by hugovk** [comment]
Ah yes, the devguide has been reorganised. Would you like to fix it? Linking to https://devguide.python.org/versions/ without the anchor would be good.

**Comment by dvarrazzo** [comment]
Tried to use the github.dev editor, but couldn't change commit message. I'm not ready yet to abandon vim and git command line...

Have #53, cheers!
