### ISSUE TITLE
Add GitHub ribbon

### ISSUE THREAD

**Issue by hugovk** [hugovk/drop-python#6]
Use the CDN method of https://github.com/simonwhitaker/github-fork-ribbon-css for all four index.html files.

**Comment by hugovk** [comment]
Use the CDN method of https://github.com/simonwhitaker/github-fork-ribbon-css

**Comment by gomgam** [comment]
I want to work on this issue.

**Comment by csnktms** [comment]
finished with it, check pr please!

**Comment by hugovk** [comment]
Fixed in #8.
